INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Tủ bếp dưới ',1),
	 ('Tủ bếp trên ',1),
	 ('Tủ bếp kịch trần ',1),
	 ('Bàn đảo bếp',1),
	 ('Đợt trang trí',1),
	 ('Bàn ăn',1),
	 ('Ghế ăn',1),
	 ('Ghế sofa văng',2),
	 ('Đôn ngồi sofa',2),
	 ('Ghế ngồi sofa',2);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Bàn trà ',2),
	 ('Ốp vách',2),
	 ('Kệ tivi gỗ CN',2),
	 ('Tủ trang trí (tủ rượu)',2),
	 ('Tủ giày Gỗ CN',2),
	 ('Giường ngủ',3),
	 ('Tap đầu giường',3),
	 ('Bàn phấn',3),
	 ('Ghế trang điểm',3),
	 ('Gương ',3);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Tủ quần áo ',3),
	 ('Ốp đầu giường',3),
	 ('Bàn làm việc (Bàn học)',3),
	 ('Kệ sách',3),
	 ('Đôn thư giãn
Ghế nghỉ',3),
	 ('Bản lề',4),
	 ('Ray ngăn kéo',4),
	 ('Ray lùa tủ áo',4),
	 ('Chống cong vênh cánh lùa tủ áo',4),
	 ('Giá bát',4);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Pittong',4),
	 ('Tay nâng ',4),
	 ('Giá xoong nồi',4),
	 ('Giá dao thớt',4),
	 ('Khay thìa dĩa',4),
	 ('Giá gia vị',4),
	 ('Kính bếp',4),
	 ('Gạch bông',4),
	 ('Đá bếp',4),
	 ('Soi đá bếp',4);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Đèn led tủ',4),
	 ('Đèn led ngăn kéo bếp',4),
	 ('Thùng rác',4),
	 ('Tay nắm cửa',4),
	 ('Bản lề',5),
	 ('Ray ngăn kéo',5),
	 ('Giá xoong nồi',5),
	 ('Giá để dao thớt',5),
	 ('Giá để gia vị',5),
	 ('Pittong nâng cánh',5);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Tủ kho 6 tầng',5),
	 ('Thùng rác',5),
	 ('Lavabo',6),
	 ('Vách kính nhà tắm',6),
	 ('Tủ bếp dưới ',7),
	 ('Tủ bếp trên',7),
	 ('Tủ bếp kịch trần ',7),
	 ('Bàn đảo bếp',7),
	 ('Đợt trang trí',7),
	 ('Bàn ăn',7);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Ghế ăn',7),
	 ('Sofa tân cổ Italia',8),
	 ('Đôn ngồi sofa',8),
	 ('Ghế ngồi sofa',8),
	 ('Bàn trà ',8),
	 ('Ốp gương tường',8),
	 ('Kệ tivi',8),
	 ('Tủ trang trí (tủ rượu)',8),
	 ('Tủ giày Gỗ CN',8),
	 ('Giường ngủ bọc da nỉ',9);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Giường ngủ khung gỗ kết hợp bọc da nỉ',9),
	 ('Tap đầu giường',9),
	 ('Bàn phấn',9),
	 ('Ghế trang điểm',9),
	 ('Gương trang điểm',9),
	 ('Tủ quần áo',9),
	 ('Ốp đầu giường',9),
	 ('Bàn làm việc (Bàn học)',9),
	 ('Đôn tư giãn',9),
	 ('Ghế nghỉ',9);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Lavabo',10),
	 ('Vách kính nhà tắm',10),
	 ('Tủ bếp dưới',11),
	 ('Tủ bếp trên ',11),
	 ('Tủ bếp kịch trần ',11),
	 ('Bàn đảo bếp',11),
	 ('Đợt trang trí',11),
	 ('Bàn ăn',11),
	 ('Ghế ăn',11),
	 ('Ghế sofa',12);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Bàn trà ',12),
	 ('Ốp vách',12),
	 ('Kệ tivi',12),
	 ('Tủ trang trí (tủ rượu)',12),
	 ('Tủ giày',12),
	 ('Giường ngủ',13),
	 ('Tap đầu giường',13),
	 ('Bàn phấn',13),
	 ('Ghế trang điểm',13),
	 ('Gương trang điểm',13);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Tủ áo',13),
	 ('Ốp đầu giường',13),
	 ('Bàn làm việc (Bàn học)',13),
	 ('Đôn tư giãn',13),
	 ('Ghế nghỉ',13),
	 ('Tủ bếp dưới ',14),
	 ('Tủ bếp trên ',14),
	 ('Tủ bếp kịch trần',14),
	 ('Bàn đảo bếp',14),
	 ('Đợt trang trí',14);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Bàn ăn',14),
	 ('Ghế ăn',14),
	 ('Ghế sofa',15),
	 ('Bàn trà ',15),
	 ('Ốp vách',15),
	 ('Kệ tivi',15),
	 ('Tủ trang trí (tủ rượu)',15),
	 ('Tủ giày',15),
	 ('Giường ngủ',16),
	 ('Tap đầu giường',16);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Bàn phấn',16),
	 ('Ghế trang điểm',16),
	 ('Gương trang điểm',16),
	 ('Tủ áo',16),
	 ('Ốp đầu giường',16),
	 ('Bàn làm việc (Bàn học)',16),
	 ('Giá sách',16),
	 ('Đôn thư giãn',16),
	 ('Ghế nghỉ',16),
	 ('Tủ bếp dưới ',17);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Tủ bếp trên ',17),
	 ('Tủ bếp kịch trần',17),
	 ('Bàn đảo bếp',17),
	 ('Tủ bếp dưới ',18),
	 ('Tủ bếp trên ',18),
	 ('Tủ bếp tầng 2',18),
	 ('Bàn đảo bếp',18),
	 ('Phát sinh ',18),
	 ('Nẹp xung quanh ',18),
	 ('Tháo dỡ sàn gõ cũ',19);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Tháo dỡ gạch ốp tường, sàn đá hoa cũ',19),
	 ('Ốp tường, sàn đá hoa',19),
	 ('Vật liệu ốp sàn bếp',19),
	 ('Hạng mục đập phá',19),
	 ('Hạng mục xây mới',19),
	 ('Trát tường',19),
	 ('Cầm cửa, trát cạnh',19),
	 ('Đổ lanh tô cửa đi mới',19),
	 ('Đóng bao phế liệu',19),
	 ('Chống thấm ',19);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Tháo, lắp điều hòa',20),
	 ('Đi dây đồngđiều hòa',20),
	 ('Nhân công đi điện, nước',20),
	 ('Dây điện ống nước, ô cắm, công tắc thay, thêm mới',20),
	 ('Tháo dỡ phần thạch cao cũ',21),
	 ('Làm mới thạch cao',21),
	 ('Phào tường Tân cổ điển',21),
	 ('Phào trần Tân cổ điển',21),
	 ('Sơn lại tường nhà',22),
	 ('Sơn lại trần nhà',22);
INSERT INTO appnoithat.hangmuc (name,noi_that_id) VALUES
	 ('Sàn gỗ An Cường 8mm',23),
	 ('Sàn gỗ An Cường xương cá 12mm kiểu công nghiệp',23),
	 ('Sàn gỗ An Cường xương cá 12mm kiểu tự nhiên',23),
	 ('Sàn gỗ JOHOR; BORNEO; SAMALAY; SEMPORNA; SMATWOOD',23),
	 ('Sàn gỗ CLASSIC FLOORING; AGT',23),
	 ('Sàn gỗ A Qua; KANSAS',23),
	 ('Phào chân tường',23),
	 ('Lót sàn',23);
