INSERT INTO appnoithat.noithat (name,phong_cach_id) VALUES
	 ('NỘI THẤT PHÒNG BẾP',1),
	 ('NỘI THẤT PHÒNG KHÁCH',1),
	 ('NỘI THẤT PHÒNG NGỦ',1),
	 ('PHỤ KIỆN EUROGOLD',1),
	 ('PHỤ KIỆN HAFELE',1),
	 ('NỘI THẤT WC',1),
	 ('NỘI THẤT PHÒNG BẾP',2),
	 ('NỘI THẤT PHÒNG KHÁCH',2),
	 ('NỘI THẤT PHÒNG NGỦ',2),
	 ('NỘI THẤT WC',2),
	 ('NỘI THẤT PHÒNG BẾP',3),
	 ('NỘI THẤT PHÒNG KHÁCH',3),
	 ('NỘI THẤT PHÒNG NGỦ',3),
	 ('NỘI THẤT PHÒNG BẾP',4),
	 ('NỘI THẤT PHÒNG KHÁCH',4),
	 ('NỘI THẤT PHÒNG NGỦ',4),
	 ('NỘI THẤT PHÒNG BẾP_ GỖ GÕ_ TƯƠNG ĐƯƠNG GỖ ÓC CHÓ',4),
	 ('NỘI THẤT PHÒNG BẾP_ INOX NHÔM KÍNH',5),
	 ('HẠNG MỤC PHÁ DỠ SỬA CHỮA XÂY MỚI',5),
	 ('HẠNG MỤC ĐIỆN NƯỚC ĐIỀU HÒA',6),
	 ('HẠNG MỤC TRẦN',6),
	 ('HẠNG MỤC SƠN ',6),
	 ('HẠNG MỤC SÀN',6)
